pool:
  vmImage: 'ubuntu-16.04'
 
variables:
  buildConfiguration: 'release'
  major: 1
  minor: 0
  patch: $[counter('myversioncounter', 0)]
 
steps:
- script: |
    dotnet build -c $(buildConfiguration)
    dotnet test tests/DependencyChecker.Tests -c $(buildConfiguration)
    dotnet pack src/DependencyChecker/DependencyChecker.csproj -c $(buildConfiguration) /p:PackageVersion=$(major).$(minor).$(patch) --output $(Build.ArtifactStagingDirectory) --no-build --no-restore
 
- task: PublishBuildArtifacts@1

- task: NuGetCommand@2
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: 'NuGetConnection'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
