pool:
  vmImage: 'ubuntu-16.04'
 
variables:
  buildConfiguration: 'release'
  major: 1
  minor: 0
  patch: $[counter('myversioncounter', 0)]
 
steps:
- script: |
    dotnet build -c $(buildConfiguration)
    dotnet test tests/DependecyChecker.Tests -c $(buildConfiguration)
    dotnet pack src/DependecyChecker/DependecyChecker.csproj -c $(buildConfiguration) /p:PackageVersion=$(major).$(minor).$(patch) --output $(Build.ArtifactStagingDirectory) --no-build --no-restore
 
- task: PublishBuildArtifacts@1